# Generated by Django 5.0.6 on 2024-05-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='link')),
                ('image_reference', models.TextField(verbose_name='string to the image in the file system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
